name: open-webui
services:
    open-webui:
        ports:
            - 3000:8080
        environment:
            - OLLAMA_BASE_URL=http://eliassen-libs-dev-ollama-1:11434
            - WEBUI_AUTH=false
        # volumes:
        #     - "open-webui:/app/backend/data"
        image: ghcr.io/open-webui/open-webui:main