services:

  nginx:
    extends:
      file: docker-compose.nginx.yml
      service: nginx
    networks:
      - expose
      - frontend
      - backend

  azurite:
    extends:
      file: docker-compose.azurite.yml
      service: azurite
    networks:
      - backend

  # keycloak:
  #   extends:
  #     file: docker-compose.keycloak.yml
  #     service: keycloak
  #   networks:
  #     - frontend
  #     - backend      

  apache-tika:
    extends:
      file: docker-compose.apache-tika.yml
      service: apache-tika
    networks:
      - backend

  smtp4dev:
    extends:
      file: docker-compose.smtp4dev.yml
      service: smtp4dev
    networks:
      - frontend
      - backend

  sql-server:
    extends:
      file: docker-compose.sql-server.yml
      service: sql-server
    networks:
      - backend

  sbert:
    extends:
      file: docker-compose.sbert.yml
      service: sbert
    deploy:
      # mode: replicated
      # replicas: 6
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - backend

  vit:
    extends:
      file: docker-compose.vit.yml
      service: vit
    deploy:
      # mode: replicated
      # replicas: 6
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - backend

  ollama:
    extends:
      file: docker-compose.ollama.yml
      service: ollama
    networks:
      - backend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  open-webui:
    extends:
      file: docker-compose.open-webui.yml
      service: open-webui
    depends_on:
      - ollama
    networks:
      - frontend
      - backend

  qdrant:
    extends:
      file: docker-compose.qdrant.yml
      service: qdrant
    networks:
      - backend

networks:
  expose:
    driver: bridge
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
    azurite-data:
    keycloak-data:
    smtp4dev-data:
    qdrant-storage:
    qdrant-snapshots:
    sqlserver-data:
