
SETLOCAL ENABLEEXTENSIONS

@ECHO OFF

SET DATABASE_APP_INSTANCE=secondshooter
SET DATABASE_APP_NAME=secondshooter
SET DACPAC_PATH=.\*.dacpac

SET DATABASE_APPLICATION_SERVER=(localdb)\%DATABASE_APP_INSTANCE%
SET DATABASE_APPLICATION_CONNECTION=server=%DATABASE_APPLICATION_SERVER%;database=%DATABASE_APP_NAME%

@ECHO ON

sqllocaldb create "%DATABASE_APP_INSTANCE%"
sqllocaldb start "%DATABASE_APP_INSTANCE%"

sqlcmd -S "%DATABASE_APPLICATION_SERVER%" -d master -Q "DROP DATABASE [%DATABASE_APP_NAME%]"
DEL "%USERPROFILE%\%DATABASE_APP_NAME%.mdf"
DEL "%USERPROFILE%\%DATABASE_APP_NAME%_*.ldf"
sqlcmd -S "%DATABASE_APPLICATION_SERVER%" -d master -Q "CREATE DATABASE [%DATABASE_APP_NAME%]"

FOR %%d IN (%DACPAC_PATH%) DO (
	sqlpackage "/SourceFile:%%d" "/TargetConnectionString:%DATABASE_APPLICATION_CONNECTION%" /Action:Publish /p:BlockOnPossibleDataLoss=false
)

@GOTO done

:error

@ECHO "Failed"

:done

ENDLOCAL