
SETLOCAL ENABLEEXTENSIONS

SET DATABASE_APP_INSTANCE=secondshooter
SET DATABASE_APP_NAME=secondshooter
SET DACPAC_PATH=.\*.dacpac

SET DATABASE_APPLICATION_SERVER=(localdb)\%DATABASE_APP_INSTANCE%
SET DATABASE_APPLICATION_CONNECTION=server=%DATABASE_APPLICATION_SERVER%;database=%DATABASE_APP_NAME%

sqllocaldb stop "%DATABASE_APP_INSTANCE%" 15.0
sqllocaldb delete "%DATABASE_APP_INSTANCE%"

RD /S/Q "%APPDATA%\..\Local\Microsoft\Microsoft SQL Server Local DB\Instances\%DATABASE_APP_NAME%"
DEL "%USERPROFILE%\%DATABASE_APP_NAME%.mdf"
DEL "%USERPROFILE%\%DATABASE_APP_NAME%_*.ldf"

ENDLOCAL

